language: php

php:
  - hhvm-3.9
  - hhvm-3.12
  - hhvm-3.15
  - hhvm-3.18


sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update

install: travis_retry composer install --no-interaction

script:
  - composer test-cl
